env: dev
app:
  name: canvas-editor-offline
  root: /Users/cheonsoo.park/Workspace/chance/canvas-editor-offline
s3:
  bucket:
    static: s3://static.devnology.com
    path: pilot
    # admin: s3://test-pddetail-admin.lotteon.com
